CTX-5757: Implemented functionality for deleting outdated images.
coretex-ai/coretexpylib pull request #174
Opened 2024-04-15 14:04 UTC by bogdant36

CTX-5757: Implemented functionality for deleting outdated images after update is done via auto-update or manual update or update after start command is called.

2024-04-16 13:52 UTC, dule1322 requested changes

2024-04-16 13:52 UTC, dule1322 commented on coretex/cli/commands/node.py
> +    node_module.removeOldImage()
Run image cleanup after node has started. Clean all images with the same repo as the image which was pulled last. Do not remove the image which is going to be used for starting the node

2024-04-17 08:07 UTC, bogdant36 commented on coretex/cli/resources/update_script_template.sh
> +image_placeholder='{{.Image}}'
The way python is formatting things kind forces me to use this as a variable so I can finish up having "{{" "}}" in actuall bash script.

2024-04-17 08:41 UTC, bogdant36 commented on coretex/cli/resources/update_script_template.sh
> +image_placeholder='{{.Image}}'
Tested it out a bit now, it can work with 4 "{" in a row, like {{{{.Image}}}}, so I will edit accordingly

2024-04-17 09:19 UTC, dule1322 requested changes

2024-04-17 09:19 UTC, dule1322 commented on coretex/cli/modules/node.py
> +
Remove newline

2024-04-17 09:19 UTC, dule1322 commented on coretex/utils/docker.py
> +            if jsonImg["Tag"] == "<none>":
You can pass in the currently used tag as a parameter to this function, and then remove all images which do not have that tag.

2024-04-18 11:46 UTC, dule1322 approved these changes

2024-04-18 11:46 UTC, merged