CTX-6016: Added prompt for endpoint invocation price if near wallet i…
coretex-ai/coretexpylib pull request #220
Opened 2024-06-26 14:12 UTC by bogdant36

…d is set.

2024-06-27 08:28 UTC, dule1322 requested changes

2024-06-27 08:28 UTC, dule1322 commented on coretex/cli/modules/node.py
> +
Delete this newline

2024-06-27 08:28 UTC, dule1322 commented on coretex/cli/modules/node.py
> +                    config_defaults.DEFAULT_ENDPOINT_INVOCATION_PRICE,
What happens if the price which is entered is 0? Should that be allowed? Can you check this with backend team

2024-06-27 08:28 UTC, dule1322 commented on coretex/cli/modules/node.py
> +                endpointInvocationPrice = clickPrompt(
Display this value in configuration preview

2024-06-27 08:29 UTC, dule1322 commented on coretex/cli/modules/node.py
> +    ) -> str:
Fix function definition formatting

2024-06-27 09:40 UTC, bogdant36 commented
Marked as draft until related backend task is merged.

2024-06-27 12:34 UTC, dule1322 commented on coretex/cli/modules/node.py
> +                        endpointInvocationPrice = 0
If a user did not enter the correct value prompt them to enter the value again

2024-06-28 13:29 UTC, dule1322 commented on coretex/cli/modules/node.py
> +def promptInvocationPrice(config: Dict[str, Any], retryCount: int = 0) -> float:
Should retry count be removed?

2024-07-01 08:27 UTC, dule1322 commented on coretex/cli/modules/node.py
> +def promptInvocationPrice(config: Dict[str, Any]) -> float:
Is config needed as a parameter?

2024-07-01 11:14 UTC, dule1322 approved these changes

2024-07-01 11:14 UTC, merged