CTX-6271: Implemented deactivate node functionality so there is no mo…
coretex-ai/coretexpylib pull request #242
Opened 2024-08-05 09:48 UTC by bogdant36

…re waiting for reconnection in 60s window when node is turned off and started again.

2024-08-05 11:16 UTC, dule1322 requested changes

2024-08-05 11:16 UTC, dule1322 commented on coretex/configuration.py
> +        config.get("nodeId") is not None
Is this change backwards compatible?

2024-08-05 11:16 UTC, dule1322 commented on coretex/cli/modules/node.py
> +        stop(config["nodeId"])
`nodeId` which is saved in `config` is of `str` type (that is what `registerNode` functions returns) but `stop` expects it to be `int`. Change `registerNode` to return a `int` properly.

2024-08-05 12:09 UTC, dule1322 commented on coretex/cli/modules/node.py
> +        "id": id,
Remove comma

2024-08-05 12:09 UTC, dule1322 commented on coretex/cli/modules/node.py
> +    params: Dict[str, Any] = {
There is no need for explicit type here

2024-08-06 08:20 UTC, VukManojlovic approved these changes

2024-08-06 12:40 UTC, dule1322 commented on coretex/cli/commands/node.py
> +        node_module.stop(config["nodeId"])
This will raise an error if `nodeId` does not exist in configuration. Use Node name to fetch the Node id if it isn't saved in the config.

2024-08-07 11:12 UTC, dule1322 approved these changes

2024-08-07 11:12 UTC, merged